
##makeCacheMatrix and cacheSove is very similar to the functions makeVector 
##and cachemean provided in the description of the programming assignment.
##The argument of the function makeCacheMatrix x is a nonsingular matrix.
## makeCacheMatrix creates a list containing functions to
##            set the value of the matrix
##            get the value of the matrix
##            set the value of the inverse matrix
##            get the value of the inverse matrix
##This list is used by the function cacheSolve as an input.

makeCacheMatrix <- function(x = matrix()) {
  inverseM <- NULL  
  set <- function(y) {
    x <<- y
    inverseM <<- NULL  
  }
  get <- function() x
  setinverse <- function(inverse) inverseM <<- inverse 
  getinverse <- function() inverseM
  list(set=set, get=get, setinverse=setinverse, getinverse=getinverse)
}

##The argument of cacheSolve will use the list generated by makeCacheMatrix.
##cacheSolve will return with the inverse of the original matrix that was 
##fed as an input to makeCacheMatrix. If the inverse has been calculated previously,
## cacheSolve gets the data from the cache (inverseM). If inverseM does not have
##the inverse matrix, cacheSolve will calculate it by calling the function solve(data) 
##where data contains the original matrix. Solve will return with error messages
##if the original matrix has no inverse. 

cacheSolve <- function(x, ...) {
  inverseM <- x$getinverse()
  if (!is.null(inverseM)){
    message("getting cached data")
    return(inverseM)
  }
  data = x$get()
  inverseM = solve(data, ...)
  x$setinverse(inverseM)
  inverseM
}
